# grafana_provisioning/datasources/prometheus.yml
apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus-ds # Unique ID for this data source
    access: proxy
    url: http://prometheus:9090 # 'prometheus' is the service name in docker-compose
    isDefault: true
    version: 1
    editable: true
